repos:
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        args: [--in-place, --remove-all-unused-imports, --remove-unused-variables]
        language: system
        types: [python]
        
      - id: isort
        name: isort
        entry: isort
        args: [--quiet, --settings-path, .isort.cfg]
        language: system
        types: [python]

      - id: black
        name: black
        entry: black
        args: [--quiet]
        language: system
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
